apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: worker-app-pod
    app: worker-voting-app
spec:
  containers:
  - name: worker-app
    image: dockersamples/examplevotingapp_worker
    resources:

